# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint & Test

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python-check.yml'
      - 'numbin/**'
      - 'test/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python-check.yml'
      - 'numbin/**'
      - 'test/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
      - name: Lint
        run: make lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
        os: [ubuntu-latest , macos-13, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Test
        env:
          PYTEST_ADDOPTS: -s
        run: make test
